version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iqp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/iqp
      SECRET_KEY: ${SECRET_KEY:-super-secret-key}
      FRONTEND_URL: http://localhost:5173
      MOCK_MODE: ${MOCK_MODE:-true}
    ports:
      - "8000:8000"
    volumes:
      - ../data/samples:/app/data/samples:ro
      - ../data/delta:/app/data/delta

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      VITE_BACKEND_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:4173"  # Vite preview

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: ""
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"

  redpanda:
    image: redpandadata/redpanda:v23.1.5
    command:
      - redpanda
      - start
      - --check=false
      - --node-id=0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --cpus=1
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    # redpanda is optional; not depended on by other services

volumes:
  postgres_data:
  grafana_data:
  redpanda_data: