name: Security Scanning

on:
  schedule:
    - cron: '0 2 * * 1'  # weekly on Monday
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install bandit pip-audit
      - name: Run bandit security scan
        run: bandit -r backend -f sarif -o bandit-results.sarif || true
      - name: Run pip-audit
        run: pip-audit --format sarif -o pip-audit-results.sarif || true
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
      - name: Upload pip-audit SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pip-audit-results.sarif

  node-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run npm audit
        run: |
          cd frontend
          npm audit --audit-level=moderate --json > npm-audit.json || true
      - name: Upload npm audit results
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit
          path: frontend/npm-audit.json